### ISSUE TITLE
[BUG] RAGTool is not able to give response.

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/skills#132]
**What is the bug?**
When asking agent on the questions: `Can you tell me what's the population increase of Seattle from 2021 to 2023 by using RAGTool?`, the agent will gives an error of
```
2024-01-16 15:28:58 | java.lang.IllegalArgumentException: Some parameter placeholder not filled in payload: prompt
-- | --
2024-01-16 15:28:58 | at org.opensearch.ml.common.connector.Connector.validatePayload(Connector.java:88) ~[opensearch-ml-common-3.0.0.0-SNAPSHOT.jar:?]
2024-01-16 15:28:58 | at org.opensearch.ml.engine.algorithms.remote.RemoteConnectorExecutor.preparePayloadAndInvokeRemoteModel(RemoteConnectorExecutor.java:118) ~[opensearch-ml-algorithms-3.0.0.0-SNAPSHOT.jar:?]
2024-01-16 15:28:58 | at org.opensearch.ml.engine.algorithms.remote.RemoteConnectorExecutor.executePredict(RemoteConnectorExecutor.java:74) ~[opensearch-ml-algorithms-3.0.0.0-SNAPSHOT.jar:?]
2024-01-16 15:28:58 | at org.opensearch.ml.engine.algorithms.remote.RemoteModel.predict(RemoteModel.java:61) ~[opensearch-ml-algorithms-3.0.0.0-SNAPSHOT.jar:?]
```

**How can one reproduce the bug?**
1. Go to Chatbot
2. Click on Chatbot button
3. Start a new conversation and ask `Can you tell me what's the population increase of Seattle from 2021 to 2023 by using RAGTool?`

**What is the expected behavior?**
It should response without error

**What is your host/environment?**
 - OS: Linux
 - Version 3.0.0
 - Plugins

**Do you have any screenshots?**
<img width="420" alt="image" src="https://github.com/opensearch-project/skills/assets/13493605/83e1e90f-3127-42aa-80d2-a2e32640fefc">

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
Thanks for opening this. Was #130 a fix?

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)

**Comment by zane-neo** [comment]
Closing this as it's fixed.
